export const SPECIALIZATIONS = [
  "Web Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Mobile App Developer",
  "Data Scientist",
  "Machine Learning Engineer",
  "Game Developer",
  "Cybersecurity Specialist",
  "Cloud Engineer",
  "Software Engineer",
  "AI Engineer",
  "Embedded Systems Developer",
  "Blockchain Developer",
] as const;

export const SKILLS = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Vue",
  "Angular",
  "Node.js",
  "Express",
  "Django",
  "Flask",
  "Spring Boot",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "AWS",
  "Azure",
  "Google Cloud",
  "Terraform",
  "Python",
  "Java",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Flutter",
  "React Native",
  "Kotlin",
  "Swift",
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Pandas",
  "NumPy",
  "Git",
  "Linux",
  "REST API",
  "GraphQL",
  "Microservices",
  "System Design",
  "Data Structures",
  "Algorithms",
] as const;
